COIN_NAME = "JAYEEEE"
COIN_SYMBOL = "JAYE"

MAX_SUPPLY = 24_000_000

BLOCK_REWARD = 50

POW_ALGORITHM = "SHA-256"
DIFFICULTY = 4

NETWORK_NAME = "JAYEEEE Network"

GENESIS_MESSAGE = "JAYEEEE Genesis Block"
